name: Coding Standards
on: [push, pull_request]

jobs:

# Runs PHP coding standards checks.
  phpcs:
    name: PHP coding standards
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate
    
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Log debug information
      run: |
        php --version
        composer --version

    - name: Install dependencies
      run: composer install

    - name: Log PHPCS debug information
      run: phpcs -i

    - name: PHP Coding Standards
      run: composer lint
    
    - name: PHPStan Static Analysis
      run: composer stan
  
    - name: PHPStan Static Analysis (dingo-d/phpstan-wp-action@v1)
      uses: dingo-d/phpstan-wp-action@v1
      with:
        error_format: github
