name: CI

on: [push]

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v2 # or alternative dependency management
    - uses: dingo-d/phpstan-wp-action@v1
    
    - name: PHPStan Static Analysis
      uses: dingo-d/phpstan-wp-action@v1
      with:
        error_format: github
        args: --debug
